---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: angular-app-deployment
  namespace: prod
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: angular-app
  template:
    metadata:
      labels:
        app : angular-app
    spec:
      containers:
        - name: deploment-container-angular
          image: katakamlokesh/angular-app:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
... 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
  name: angular-app-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: angular-app
...
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
  name: angular-service-loadbalancer
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: angular-app 
...    
