---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-test-service
  namespace: prod
  labels: 
    app: backend
spec: 
  ports:
    - port: 3306
      targetPort: 3306 
  clusterIP: None
  selector: 
    app: backend
...
