---
apiVersion: v1
kind: Pod
metadata:
  name: test-ed
spec:
  containers:
  - name: test-container
    image: redis 
    volumeMounts:
      - name: cache-volume
        mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir: {}
...

