---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
 template:
   metadata:
     labels:
       name: fluentd
   spec:
     containers:
       - name: fluentd
         image: fluentd
 selector:
   matchLabels:
     name: fluentd
...

