---
apiVersion: v1
kind: Pod
metadata:
  name: busybox 
spec: 
  containers:
    - name: busybox-container
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
       - name: SPECIAL_LEVEL_KEY
         valueFrom:
           configMapKeyRef:
             name: special-config
             key: special.how    
  restartPolicy: Never
...

