---
apiVersion: v1
kind: Pod
metadata: 
  name: redis
spec: 
  containers:
   - name: redis
     image: redis
     volumeMounts:
       - name: config-vol
         mountPath: /redis-master
  volumes:
    - name: config-vol
      configMap:
        name: example-redis-config
        items:
          - key: redis-config
            path: redis-config
...

