---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    author: lokesh
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: lokesh@007
...

