---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
spec:
  replicas: 3
  selector:
    app: frontend
  template:
    metadata:
      name: httpd-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: appserver
        image: httpd
        ports:
        - containerPort: 80
          hostPort: 9999
...

