---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: dev
  labels:
    name: jenkins-Service
    author: lokesh
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    name: jenkins-pod
    author: lokesh
    type: ci-cd
...
